spring:
    application:
        name: ids
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
            # Set this to "create" the first time you run the project with your database open and running
            # It generates your DB tables etc
            # After first run stop project, set this to "update" and run again to use
    datasource:
        url: jdbc:postgresql://localhost:5432/ids
        driverClassName: org.postgresql.Driver
        username: utente
        password: pass

#server:
#    port: 8080
#    address: localhost
