/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.ids.studenti.ll.app;


import it.unicam.ids.studenti.ll.utilities.TestConnection;

public class App {
    public static void main(String[] args) {
        System.out.println( TestConnection.hello());
    }
}
