/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.ids.studenti.ll.app;

import it.unicam.ids.studenti.ll.model.Cliente;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.HashSet;
import java.util.Set;

@SpringBootApplication
public class App {
    public Set<Cliente> clienti = new HashSet<>();
    
    public static void main(String[] args) {
        System.out.println("Hello World!!");
    }
}
