/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.ids.studenti.ll.model;

import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertThrows;

class AziendaTest {
    @Test
    void testConnection() {
        assertThrows(
                IllegalArgumentException.class,
                () -> new Azienda("Unicum & CO.",LocalDate.of(2000,10,25))
        );
        Azienda azienda = new Azienda("Unicum & CO.",LocalDate.of(2000,10,25));
        azienda.setEmail("antonio.gassner@gmail.com");
    }
}


